# modgodb database connection config
[MongoDB]
DBURL = "localhost:27017"
DBName = "post"
UserName = "poster"
Password = "post123456"
Enable = true

[BlockChain]
Chain = "ftm"
StableHeight = 10 # stable height
GetLogsMaxBlocks = 20 # max blocks every getLogs
GetLogsInterval = 10 # seconds interval every getLogs
SyncNumber = 100

#post register
[Register]
Rpc = "http://127.0.0.1:11556/rpc"
Enable = false

[Approve]
TokenAddress = "0xaF0A46d3700E23a98F38079cE217742c92aa66aC"
LogAddress2 = [
	#"0xaF0A46d3700E23a98F38079cE217742c92aa66aC", # anyBNB
]

[BridgeToken]
Include = true # true: include, false: exclude
# token, index to compare
Topic = [
	"0x...,1",
	"0x...,2",
]
# compare
RouterAddress = "0x..."
# address whose appoved
TokenAddress = [
	"0x...",
]
