# modgodb database connection config
[MongoDB]
DBURL = "localhost:27017"
DBName = "post"
UserName = "poster"
Password = "123456"
Enable = true

# query server mongodb info
[MongoDBServer]
DBURLs = ["localhost:27017"]
DBName = "post"
UserName = "poster"
Password = "123456"

[BlockChain]
Chain = "btc"
StableHeight = 2
ScanBackHeight = 10
GetLogsMaxBlocks = 10 # max blocks every getLogs
GetLogsInterval = 60 # seconds interval every getLogs
SyncNumber = 2

[[Tokens]]
TxType = "swapin"
PairID = "BTC"
SwapServer = "http://127.0.0.1:11556/rpc"
DbName = "BTC2BSC"
TokenAddress = "native"
DepositAddress = "0xaF0A46d3700E23a98F38079cE217742c92aa66aC"

[[Tokens]]
TxType = "swapout"
PairID = "BTC"
SwapServer = "http://127.0.0.1:33556/rpc"
DbName = "BTC2ETH"
TokenAddress = "0x71b8c4d7d28d5f7edadbea5457db3b4f7f837b74"

