#
[MongoDB]
DBURL = "172.26.142.156:27037"
DBName = "swappost"
UserName = "poster"
Password = "p@st_2021052515"
Enable = true

[BlockChain]
Chain = "bsc"
StableHeight = 18
ScanBackHeight = 2500
GetLogsMaxBlocks = 20 # max blocks every getLogs
GetLogsInterval = 10 # seconds interval every getLogs
SyncNumber = 100

#post register
[Register]
Rpc = "http://172.26.142.157:38955/rpc"
Enable = false

[[Tokens]]
TxType = "anycallswap"
ChainID = "56"
SwapServer = "http://172.26.142.145:43747/rpc"
RouterContract = "0x37414a8662bc1d25be3ee51fb27c2686e2490a89"
Whitelist = [
]

